version: 2.1


orbs:
  codecov: codecov/codecov@3.1.1
  go: circleci/go@1.7.0

jobs:
  test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - run: go mod tidy
      - go/test:
          covermode: atomic
          failfast: true
          race: true
          coverprofile: coverage.html
workflows:
  main:
    jobs:
      - test:
          post-steps:
            - codecov/upload:
                file: coverage.html

